# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: #Event is triggered ( series of commands when a  code is pushed or PR is created) testing - testing
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs: #Jobs - Every Job runs in 
  build:

    runs-on: ${{matrix.os}} #ubuntu-latest (Docker preinstalled),windows-latest,macOs-latest #Runs on ubuntu, windows or mac OS
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps: # Steps followed by actions
    - uses: actions/checkout@v3 # Here's an example of an action that performs a git checkout of a repository.
    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Installs dependencies - Java
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Run chmod to make gradlew executable # Runs the commands
      run: chmod +x ./gradlew
      
    - name: Build with Gradle # Builds the code
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Build and push docker image to Docker Hub # docker login cred     docker build     docker tag # https://github.com/marketplace/actions/docker-build-push-action
      uses: mr-smithers-excellent/docker-build-push@v6 #action with v6
      with:
        image: don31658/githubactions1 #Parameters to overwrite Docker ID and repo name
        tags: v1, latest
        dockerfile: ./Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
